### ISSUE TITLE
Git hook to autoformat source code

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/brackit#16]
We need a pre commit hook or something like that to auto-format code according to our IntelliJ Java Formatter or the Kotlin standard code formatting rules.

**Comment by ksclarke** [comment]
Are you specifically looking for a git hook vs. a Maven plugin that runs and formats with the build?

**Comment by JohannesLichtenberger** [comment]
I don't know... it's always best effort and the user has to auto-format I guess (otherwise I'd think a new commit based on auto-formatted code would be strange).

**Comment by ksclarke** [comment]
I'm a fan of this plugin: https://code.revelc.net/formatter-maven-plugin/format-mojo.html -- of course, you have to do a project wide reformat first so that any new commits that are auto-formatted don't have crazy diffs.

Do you all use the standard IntelliJ settings (which are the standard Java/Kotlin ones?) or is there a custom format? This plugin uses the Eclipse engine. I'd be curious to see if there are differences.

**Comment by ksclarke** [comment]
With the merge of the autoformatter, do you want to do a PR that runs the formatter and includes all the changes in a standalone formatting commit? I can do this as well if you'd like. I just wanted to keep the formatting update separate from the commit/PR that added the formatting.

**Comment by JohannesLichtenberger** [comment]
Sounds good 👍
